# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tempiex/api/common/v1/message.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tempiex/api/common/v1/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from tempiex.api.enums.v1 import workflow_pb2 as tempiex_dot_api_dot_enums_dot_v1_dot_workflow__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#tempiex/api/common/v1/message.proto\x12\x15tempiex.api.common.v1\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#tempiex/api/enums/v1/workflow.proto\")\n\x07Payload\x12\x10\n\x08\x65ncoding\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"<\n\x08Payloads\x12\x30\n\x08payloads\x18\x01 \x03(\x0b\x32\x1e.tempiex.api.common.v1.Payload\"8\n\x11WorkflowExecution\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x0e\n\x06run_id\x18\x02 \x01(\t\"\x1c\n\x0cWorkflowType\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\x0c\x41\x63tivityType\x12\x0c\n\x04name\x18\x01 \x01(\t\"r\n\x06Header\x12\x39\n\x06\x66ields\x18\x01 \x03(\x0b\x32).tempiex.api.common.v1.Header.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"\xba\x02\n\x15WorkflowExecutionInfo\x12;\n\texecution\x18\x01 \x01(\x0b\x32(.tempiex.api.common.v1.WorkflowExecution\x12\x31\n\x04type\x18\x02 \x01(\x0b\x32#.tempiex.api.common.v1.WorkflowType\x12.\n\nstart_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nclose_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12=\n\x06status\x18\x05 \x01(\x0e\x32-.tempiex.api.enums.v1.WorkflowExecutionStatus\x12\x12\n\ntask_queue\x18\x06 \x01(\tBCZAgithub.com/tempiex/tempiex/api/gen/tempiex/api/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tempiex.api.common.v1.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZAgithub.com/tempiex/tempiex/api/gen/tempiex/api/common/v1;commonv1'
  _globals['_HEADER_FIELDSENTRY']._loaded_options = None
  _globals['_HEADER_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_PAYLOAD']._serialized_start=159
  _globals['_PAYLOAD']._serialized_end=200
  _globals['_PAYLOADS']._serialized_start=202
  _globals['_PAYLOADS']._serialized_end=262
  _globals['_WORKFLOWEXECUTION']._serialized_start=264
  _globals['_WORKFLOWEXECUTION']._serialized_end=320
  _globals['_WORKFLOWTYPE']._serialized_start=322
  _globals['_WORKFLOWTYPE']._serialized_end=350
  _globals['_ACTIVITYTYPE']._serialized_start=352
  _globals['_ACTIVITYTYPE']._serialized_end=380
  _globals['_HEADER']._serialized_start=382
  _globals['_HEADER']._serialized_end=496
  _globals['_HEADER_FIELDSENTRY']._serialized_start=451
  _globals['_HEADER_FIELDSENTRY']._serialized_end=496
  _globals['_WORKFLOWEXECUTIONINFO']._serialized_start=499
  _globals['_WORKFLOWEXECUTIONINFO']._serialized_end=813
# @@protoc_insertion_point(module_scope)
