# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tempiex/api/enums/v1/workflow.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tempiex/api/enums/v1/workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#tempiex/api/enums/v1/workflow.proto\x12\x14tempiex.api.enums.v1*\xb6\x02\n\x17WorkflowExecutionStatus\x12)\n%WORKFLOW_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12%\n!WORKFLOW_EXECUTION_STATUS_RUNNING\x10\x01\x12\'\n#WORKFLOW_EXECUTION_STATUS_COMPLETED\x10\x02\x12$\n WORKFLOW_EXECUTION_STATUS_FAILED\x10\x03\x12\'\n#WORKFLOW_EXECUTION_STATUS_CANCELLED\x10\x04\x12\'\n#WORKFLOW_EXECUTION_STATUS_TIMED_OUT\x10\x05\x12(\n$WORKFLOW_EXECUTION_STATUS_TERMINATED\x10\x06*\xa2\x05\n\tEventType\x12\x1a\n\x16\x45VENT_TYPE_UNSPECIFIED\x10\x00\x12)\n%EVENT_TYPE_WORKFLOW_EXECUTION_STARTED\x10\x01\x12&\n\"EVENT_TYPE_WORKFLOW_TASK_SCHEDULED\x10\x02\x12$\n EVENT_TYPE_WORKFLOW_TASK_STARTED\x10\x03\x12&\n\"EVENT_TYPE_WORKFLOW_TASK_COMPLETED\x10\x04\x12&\n\"EVENT_TYPE_ACTIVITY_TASK_SCHEDULED\x10\x05\x12$\n EVENT_TYPE_ACTIVITY_TASK_STARTED\x10\x06\x12&\n\"EVENT_TYPE_ACTIVITY_TASK_COMPLETED\x10\x07\x12#\n\x1f\x45VENT_TYPE_ACTIVITY_TASK_FAILED\x10\x08\x12+\n\'EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED\x10\t\x12(\n$EVENT_TYPE_WORKFLOW_EXECUTION_FAILED\x10\n\x12+\n\'EVENT_TYPE_WORKFLOW_EXECUTION_CANCELLED\x10\x0b\x12+\n\'EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT\x10\x0c\x12,\n(EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED\x10\r\x12*\n&EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED\x10\x0e\x12\x32\n.EVENT_TYPE_WORKFLOW_EXECUTION_CANCEL_REQUESTED\x10\x0f*\xe9\x01\n\x0b\x43ommandType\x12\x1c\n\x18\x43OMMAND_TYPE_UNSPECIFIED\x10\x00\x12\'\n#COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK\x10\x01\x12,\n(COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION\x10\x02\x12(\n$COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION\x10\x03\x12;\n7COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION\x10\x04\x42\x41Z?github.com/tempiex/tempiex/api/gen/tempiex/api/enums/v1;enumsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tempiex.api.enums.v1.workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/tempiex/tempiex/api/gen/tempiex/api/enums/v1;enumsv1'
  _globals['_WORKFLOWEXECUTIONSTATUS']._serialized_start=62
  _globals['_WORKFLOWEXECUTIONSTATUS']._serialized_end=372
  _globals['_EVENTTYPE']._serialized_start=375
  _globals['_EVENTTYPE']._serialized_end=1049
  _globals['_COMMANDTYPE']._serialized_start=1052
  _globals['_COMMANDTYPE']._serialized_end=1285
# @@protoc_insertion_point(module_scope)
