# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tempiex.api.workflowservice.v1 import service_pb2 as tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tempiex/api/workflowservice/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkflowServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNamespace = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/RegisterNamespace',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RegisterNamespaceRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RegisterNamespaceResponse.FromString,
                _registered_method=True)
        self.DescribeNamespace = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/DescribeNamespace',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeNamespaceRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeNamespaceResponse.FromString,
                _registered_method=True)
        self.StartWorkflowExecution = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/StartWorkflowExecution',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.StartWorkflowExecutionRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.StartWorkflowExecutionResponse.FromString,
                _registered_method=True)
        self.DescribeWorkflowExecution = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/DescribeWorkflowExecution',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeWorkflowExecutionRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeWorkflowExecutionResponse.FromString,
                _registered_method=True)
        self.GetWorkflowExecutionHistory = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/GetWorkflowExecutionHistory',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.GetWorkflowExecutionHistoryRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.GetWorkflowExecutionHistoryResponse.FromString,
                _registered_method=True)
        self.PollWorkflowTaskQueue = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/PollWorkflowTaskQueue',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollWorkflowTaskQueueRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollWorkflowTaskQueueResponse.FromString,
                _registered_method=True)
        self.RespondWorkflowTaskCompleted = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/RespondWorkflowTaskCompleted',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondWorkflowTaskCompletedRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondWorkflowTaskCompletedResponse.FromString,
                _registered_method=True)
        self.PollActivityTaskQueue = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/PollActivityTaskQueue',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollActivityTaskQueueRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollActivityTaskQueueResponse.FromString,
                _registered_method=True)
        self.RespondActivityTaskCompleted = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/RespondActivityTaskCompleted',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskCompletedRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskCompletedResponse.FromString,
                _registered_method=True)
        self.RespondActivityTaskFailed = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/RespondActivityTaskFailed',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskFailedRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskFailedResponse.FromString,
                _registered_method=True)
        self.RecordActivityTaskHeartbeat = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/RecordActivityTaskHeartbeat',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RecordActivityTaskHeartbeatRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RecordActivityTaskHeartbeatResponse.FromString,
                _registered_method=True)
        self.SignalWorkflowExecution = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/SignalWorkflowExecution',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.SignalWorkflowExecutionRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.SignalWorkflowExecutionResponse.FromString,
                _registered_method=True)
        self.RequestCancelWorkflowExecution = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/RequestCancelWorkflowExecution',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RequestCancelWorkflowExecutionRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RequestCancelWorkflowExecutionResponse.FromString,
                _registered_method=True)
        self.TerminateWorkflowExecution = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/TerminateWorkflowExecution',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.TerminateWorkflowExecutionRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.TerminateWorkflowExecutionResponse.FromString,
                _registered_method=True)
        self.QueryWorkflow = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/QueryWorkflow',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.QueryWorkflowRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.QueryWorkflowResponse.FromString,
                _registered_method=True)
        self.CountWorkflowExecutions = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/CountWorkflowExecutions',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.CountWorkflowExecutionsRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.CountWorkflowExecutionsResponse.FromString,
                _registered_method=True)
        self.ListWorkflowExecutions = channel.unary_unary(
                '/tempiex.api.workflowservice.v1.WorkflowService/ListWorkflowExecutions',
                request_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.ListWorkflowExecutionsRequest.SerializeToString,
                response_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.ListWorkflowExecutionsResponse.FromString,
                _registered_method=True)


class WorkflowServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartWorkflowExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeWorkflowExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowExecutionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollWorkflowTaskQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondWorkflowTaskCompleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollActivityTaskQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondActivityTaskCompleted(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondActivityTaskFailed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordActivityTaskHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignalWorkflowExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestCancelWorkflowExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateWorkflowExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountWorkflowExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkflowExecutions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkflowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNamespace,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RegisterNamespaceRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RegisterNamespaceResponse.SerializeToString,
            ),
            'DescribeNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeNamespace,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeNamespaceRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeNamespaceResponse.SerializeToString,
            ),
            'StartWorkflowExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorkflowExecution,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.StartWorkflowExecutionRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.StartWorkflowExecutionResponse.SerializeToString,
            ),
            'DescribeWorkflowExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeWorkflowExecution,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeWorkflowExecutionRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeWorkflowExecutionResponse.SerializeToString,
            ),
            'GetWorkflowExecutionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowExecutionHistory,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.GetWorkflowExecutionHistoryRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.GetWorkflowExecutionHistoryResponse.SerializeToString,
            ),
            'PollWorkflowTaskQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.PollWorkflowTaskQueue,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollWorkflowTaskQueueRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollWorkflowTaskQueueResponse.SerializeToString,
            ),
            'RespondWorkflowTaskCompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondWorkflowTaskCompleted,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondWorkflowTaskCompletedRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondWorkflowTaskCompletedResponse.SerializeToString,
            ),
            'PollActivityTaskQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.PollActivityTaskQueue,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollActivityTaskQueueRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollActivityTaskQueueResponse.SerializeToString,
            ),
            'RespondActivityTaskCompleted': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondActivityTaskCompleted,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskCompletedRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskCompletedResponse.SerializeToString,
            ),
            'RespondActivityTaskFailed': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondActivityTaskFailed,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskFailedRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskFailedResponse.SerializeToString,
            ),
            'RecordActivityTaskHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordActivityTaskHeartbeat,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RecordActivityTaskHeartbeatRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RecordActivityTaskHeartbeatResponse.SerializeToString,
            ),
            'SignalWorkflowExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.SignalWorkflowExecution,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.SignalWorkflowExecutionRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.SignalWorkflowExecutionResponse.SerializeToString,
            ),
            'RequestCancelWorkflowExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestCancelWorkflowExecution,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RequestCancelWorkflowExecutionRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RequestCancelWorkflowExecutionResponse.SerializeToString,
            ),
            'TerminateWorkflowExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateWorkflowExecution,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.TerminateWorkflowExecutionRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.TerminateWorkflowExecutionResponse.SerializeToString,
            ),
            'QueryWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryWorkflow,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.QueryWorkflowRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.QueryWorkflowResponse.SerializeToString,
            ),
            'CountWorkflowExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.CountWorkflowExecutions,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.CountWorkflowExecutionsRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.CountWorkflowExecutionsResponse.SerializeToString,
            ),
            'ListWorkflowExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkflowExecutions,
                    request_deserializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.ListWorkflowExecutionsRequest.FromString,
                    response_serializer=tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.ListWorkflowExecutionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tempiex.api.workflowservice.v1.WorkflowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tempiex.api.workflowservice.v1.WorkflowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkflowService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/RegisterNamespace',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RegisterNamespaceRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RegisterNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/DescribeNamespace',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeNamespaceRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartWorkflowExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/StartWorkflowExecution',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.StartWorkflowExecutionRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.StartWorkflowExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeWorkflowExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/DescribeWorkflowExecution',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeWorkflowExecutionRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.DescribeWorkflowExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowExecutionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/GetWorkflowExecutionHistory',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.GetWorkflowExecutionHistoryRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.GetWorkflowExecutionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollWorkflowTaskQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/PollWorkflowTaskQueue',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollWorkflowTaskQueueRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollWorkflowTaskQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondWorkflowTaskCompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/RespondWorkflowTaskCompleted',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondWorkflowTaskCompletedRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondWorkflowTaskCompletedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollActivityTaskQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/PollActivityTaskQueue',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollActivityTaskQueueRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.PollActivityTaskQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondActivityTaskCompleted(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/RespondActivityTaskCompleted',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskCompletedRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskCompletedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondActivityTaskFailed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/RespondActivityTaskFailed',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskFailedRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RespondActivityTaskFailedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordActivityTaskHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/RecordActivityTaskHeartbeat',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RecordActivityTaskHeartbeatRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RecordActivityTaskHeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignalWorkflowExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/SignalWorkflowExecution',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.SignalWorkflowExecutionRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.SignalWorkflowExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestCancelWorkflowExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/RequestCancelWorkflowExecution',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RequestCancelWorkflowExecutionRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.RequestCancelWorkflowExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TerminateWorkflowExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/TerminateWorkflowExecution',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.TerminateWorkflowExecutionRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.TerminateWorkflowExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/QueryWorkflow',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.QueryWorkflowRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.QueryWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountWorkflowExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/CountWorkflowExecutions',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.CountWorkflowExecutionsRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.CountWorkflowExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkflowExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tempiex.api.workflowservice.v1.WorkflowService/ListWorkflowExecutions',
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.ListWorkflowExecutionsRequest.SerializeToString,
            tempiex_dot_api_dot_workflowservice_dot_v1_dot_service__pb2.ListWorkflowExecutionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
