syntax = "proto3";
package tempiex.api.enums.v1;
option go_package = "github.com/tempiex/tempiex/api/gen/tempiex/api/enums/v1;enumsv1";

enum WorkflowExecutionStatus {
  WORKFLOW_EXECUTION_STATUS_UNSPECIFIED = 0;
  WORKFLOW_EXECUTION_STATUS_RUNNING = 1;
  WORKFLOW_EXECUTION_STATUS_COMPLETED = 2;
  WORKFLOW_EXECUTION_STATUS_FAILED = 3;
  WORKFLOW_EXECUTION_STATUS_CANCELLED = 4;
  WORKFLOW_EXECUTION_STATUS_TIMED_OUT = 5;
  WORKFLOW_EXECUTION_STATUS_TERMINATED = 6;
}

enum EventType {
  EVENT_TYPE_UNSPECIFIED = 0;
  EVENT_TYPE_WORKFLOW_EXECUTION_STARTED = 1;
  EVENT_TYPE_WORKFLOW_TASK_SCHEDULED = 2;
  EVENT_TYPE_WORKFLOW_TASK_STARTED = 3;
  EVENT_TYPE_WORKFLOW_TASK_COMPLETED = 4;
  EVENT_TYPE_ACTIVITY_TASK_SCHEDULED = 5;
  EVENT_TYPE_ACTIVITY_TASK_STARTED = 6;
  EVENT_TYPE_ACTIVITY_TASK_COMPLETED = 7;
  EVENT_TYPE_ACTIVITY_TASK_FAILED = 8;
  EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED = 9;
  EVENT_TYPE_WORKFLOW_EXECUTION_FAILED = 10;
  EVENT_TYPE_WORKFLOW_EXECUTION_CANCELLED = 11;
  EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT = 12;
  EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED = 13;
  EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED = 14;
  EVENT_TYPE_WORKFLOW_EXECUTION_CANCEL_REQUESTED = 15;
}

enum CommandType {
  COMMAND_TYPE_UNSPECIFIED = 0;
  COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK = 1;
  COMMAND_TYPE_COMPLETE_WORKFLOW_EXECUTION = 2;
  COMMAND_TYPE_FAIL_WORKFLOW_EXECUTION = 3;
  COMMAND_TYPE_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION = 4;
}
